sync

diff --git a/sys/net/pf_forward/Makefile b/sys/net/pf_forward/Makefile
--- a/sys/net/pf_forward/Makefile
+++ b/sys/net/pf_forward/Makefile
@@ -1,4 +1,4 @@
-#	$OpenBSD: Makefile,v 1.3 2012/07/10 16:58:29 bluhm Exp $
+#	$OpenBSD: Makefile,v 1.7 2014/07/13 01:47:20 bluhm Exp $
 
 # The following ports must be installed:
 #
@@ -6,66 +6,83 @@
 # py-libdnet          python interface to libdnet
 # scapy               powerful interactive packet manipulation in python
 
+# Check wether all required python packages are installed.  If some
+# are missing print a warning and skip the tests, but do not fail.
+PYTHON_IMPORT != python2.7 -c 'from scapy.all import *' 2>&1 || true
+.if ! empty(PYTHON_IMPORT)
+regress:
+	@echo '${PYTHON_IMPORT}'
+	@echo install python and the scapy module for additional tests
+.endif
+
 # This test needs a manual setup of four machines
 # The setup is the same as for regress/sys/net/pf_fragment
-# Set up machines: SRC PF RT DST
+# Set up machines: SRC PF RT ECO
 # SRC is the machine where this makefile is running.
 # PF is running OpenBSD forwarding through pf, it is the test target.
 # RT is a router forwarding packets, maximum MTU is 1300.
-# DST is reflecting the ping and UDP and TCP echo packets.
-# RDR does not exist, PF redirects the traffic to DST.
-# AF does not exist, PF translates address family and sends to DST.
+# ECO is reflecting the ping and UDP and TCP echo packets.
+# RDR does not exist, PF redirects the traffic to ECO.
+# AF does not exist, PF translates address family and sends to ECO.
 #
-# +---+   1   +--+   2   +--+   3   +---+   4   +---+  5  +--+
-# |SRC| ----> |PF| ----> |RT| ----> |DST|       |RDR|     |AF|
+# +---+   0   +--+   1   +--+   2   +---+   3   +---+  4  +--+
+# |SRC| ----> |PF| ----> |RT| ----> |ECO|       |RDR|     |AF|
 # +---+       +--+       +--+       +---+       +---+     +--+
 #     out    in  out    in  out    in          in        in
 
-# Configure Addresses on the machines, there must be routes for the networks.
-# Adapt interface and addresse variables to your local setup.
+# Configure Addresses on the machines, there must be routes for the
+# networks.  Adapt interface and addresse variables to your local
+# setup.  To control the remote machine you need a hostname for
+# ssh to log in.
+# You must have an anchor "regress" for the divert rules in the pf.conf
+# of the PF machine.  The kernel of the PF machine gets testet.
 #
-SRC_IF =	tun0
-SRC_MAC =	fe:e1:ba:d1:0a:dc
-PF_MAC =	52:54:00:12:34:50
+# Run make check-setup to see if you got the setup correct.
 
-SRC_OUT =	10.188.211.10
-PF_IN =		10.188.211.50
-PF_OUT =	10.188.212.50
-RT_IN =		10.188.212.51
-RT_OUT =	10.188.213.51
-DST_IN =	10.188.213.52
-RDR_IN =	10.188.214.1
-AF_IN =		10.188.215.82
+SRC_IF ?=	tun0
+SRC_MAC ?=	fe:e1:ba:d1:0a:dc
+PF_MAC ?=	52:54:00:12:34:50
+PF_SSH ?=
+RT_SSH ?=
+ECO_SSH ?=
 
-SRC_OUT6 =	fdd7:e83e:66bc:211:fce1:baff:fed1:561f
-PF_IN6 =	fdd7:e83e:66bc:211:5054:ff:fe12:3450
-PF_OUT6 =	fdd7:e83e:66bc:212:5054:ff:fe12:3450
-RT_IN6 =	fdd7:e83e:66bc:212:5054:ff:fe12:3451
-RT_OUT6 =	fdd7:e83e:66bc:213:5054:ff:fe12:3451
-DST_IN6 =	fdd7:e83e:66bc:213:5054:ff:fe12:3452
-RDR_IN6 =	fdd7:e83e:66bc:214::1
-AF_IN6 =	fdd7:e83e:66bc:215:5054:ff:fe12:3434
+SRC_OUT ?=	10.188.210.10
+PF_IN ?=	10.188.210.50
+PF_OUT ?=	10.188.211.50
+RT_IN ?=	10.188.211.51
+RT_OUT ?=	10.188.212.51
+ECO_IN ?=	10.188.212.52
+RDR_IN ?=	10.188.213.188
+AF_IN ?=	10.188.214.82		# /24 must be dec(ECO_IN6/120)
 
-# pf rules on PF must look like this:
-#
-# pass to { $PF_IN/24 $PF_IN6/64 }
-# pass to { $RT_IN/24 $RT_IN6/64 }
-# pass to { $DST_IN/24 $DST_IN6/64 }
-# pass to { $RDR_IN/24 $RDR_IN6/64 }
-#
-# pass in  to $RDR_IN/24  rdr-to $DST_IN  tag rdr
-# pass out                nat-to $PF_OUT  tagged rdr
-# pass in  to $RDR_IN6/64 rdr-to $DST_IN6 tag rdr
-# pass out                nat-to $PF_OUT6 tagged rdr
+SRC_OUT6 ?=	fdd7:e83e:66bc:210:fce1:baff:fed1:561f
+PF_IN6 ?=	fdd7:e83e:66bc:210:5054:ff:fe12:3450
+PF_OUT6 ?=	fdd7:e83e:66bc:211:5054:ff:fe12:3450
+RT_IN6 ?=	fdd7:e83e:66bc:211:5054:ff:fe12:3451
+RT_OUT6 ?=	fdd7:e83e:66bc:212:5054:ff:fe12:3451
+ECO_IN6 ?=	fdd7:e83e:66bc:212:5054:ff:fe12:3452
+RDR_IN6 ?=	fdd7:e83e:66bc:213::188
+AF_IN6 ?=	fdd7:e83e:66bc:214::34	# /120 must be hex(ECO_IN/24)
 
-# pass in  to $AF_IN/24  af-to inet6 from $PF_OUT6 to $DST_IN6/120 tag af
-# pass out                     inet6                               tagged af
-# pass in  to $AF_IN6/64 af-to inet  from $PF_OUT  to $DST_IN/24   tag af
-# pass out                     inet                                tagged af
+.if empty (PF_SSH) || empty (RT_SSH) || empty (ECO_SSH)
+regress:
+	@echo this tests needs three remote machines to operate on
+	@echo PF_SSH RT_SSH ECO_SSH are empty
+	@echo fill out these variables for additional tests, then
+	@echo check wether your test machines are set up properly
+.endif
 
-# Currently these test fail as pf does not fix the checksum of
-# NATed packets inside of icmp packets.
-# ping6-mtu
+.MAIN: all
+
+.if ! empty (PF_SSH)
+.if make (regress) || make (all)
+.BEGIN: pf.conf addr.py
+	@echo
+	${SUDO} true
+	ssh -t ${PF_SSH} ${SUDO} true
+	rm -f stamp-pfctl
+.endif
+.endif
 
 depend: addr.py
 
@@ -75,52 +92,42 @@ addr.py: Makefile
 	echo 'SRC_IF="${SRC_IF}"' >>$@.tmp
 	echo 'SRC_MAC="${SRC_MAC}"' >>$@.tmp
 	echo 'PF_MAC="${PF_MAC}"' >>$@.tmp
-.for var in SRC_OUT PF_IN PF_OUT RT_IN RT_OUT DST_IN RDR_IN AF_IN
+.for var in SRC_OUT PF_IN PF_OUT RT_IN RT_OUT ECO_IN RDR_IN AF_IN
 	echo '${var}="${${var}}"' >>$@.tmp
 	echo '${var}6="${${var}6}"' >>$@.tmp
 .endfor
 	mv $@.tmp $@
 
-# Make sure that the routing table on the SRC machine is correct.
-# All packets must be forwarded to PF target machine.
-TARGETS +=	route route6
+# load the pf rules into the kernel of the PF machine
+stamp-pfctl: addr.py
+	cat addr.py ${.CURDIR}/pf.conf | \
+	    ssh ${PF_SSH} ${SUDO} pfctl -a regress -f -
+	@date >$@
 
-run-regress-route:
-	@echo '\n======== $@ ========'
-	@echo Check route SRC_OUT:
-	route -n get -inet ${SRC_OUT} | fgrep -q 'interface: lo0'
-	@echo Check route PF_IN:
-	route -n get -inet ${PF_IN} | fgrep -q 'if address: ${SRC_OUT}'
-.for ip in PF_OUT RT_IN RT_OUT DST_IN RDR_IN AF_IN
-	@echo Check route ${ip}:
-	route -n get -inet ${${ip}} | fgrep -q 'gateway: ${PF_IN}'
-.endfor
-
-run-regress-route6:
-	@echo '\n======== $@ ========'
-	@echo Check route SRC_OUT6:
-	route -n get -inet6 ${SRC_OUT6} | fgrep -q 'interface: lo0'
-.for ip in PF_OUT RT_IN RT_OUT DST_IN RDR_IN AF_IN
-	@echo Check route ${ip}6:
-	route -n get -inet6 ${${ip}6} | fgrep -q 'gateway: ${PF_IN6}'
-.endfor
+# Set variables so that make runs with and without obj directory.
+# Only do that if necessary to keep visible output short.
+.if ${.CURDIR} == ${.OBJDIR}
+PYTHON =	python2.7 ./
+.else
+PYTHON =	PYTHONPATH=${.OBJDIR} python2.7 ${.CURDIR}/
+.endif
 
 # Ping all addresses.  This ensures that the ip addresses are configured
 # and all routing table are set up to allow bidirectional packet flow.
 # Note that RDR does not exist physically.  So this traffic is rewritten
-# by PF and handled by DST.
+# by PF and handled by ECO.
 TARGETS +=	ping  ping6
 
-run-regress-ping:
+run-regress-ping: stamp-pfctl
 	@echo '\n======== $@ ========'
-.for ip in SRC_OUT PF_IN PF_OUT RT_IN RT_OUT DST_IN RDR_IN AF_IN
+.for ip in SRC_OUT PF_IN PF_OUT RT_IN RT_OUT ECO_IN RDR_IN AF_IN
 	@echo Check ping ${ip}:
 	ping -n -c 1 ${${ip}}
 .endfor
 
-run-regress-ping6:
+run-regress-ping6: stamp-pfctl
 	@echo '\n======== $@ ========'
-.for ip in SRC_OUT PF_IN PF_OUT RT_IN RT_OUT DST_IN RDR_IN AF_IN
+.for ip in SRC_OUT PF_IN PF_OUT RT_IN RT_OUT ECO_IN RDR_IN AF_IN
 	@echo Check ping ${ip}6:
 	ping6 -n -c 1 ${${ip}6}
 .endfor
@@ -133,38 +140,38 @@ run-regress-ping6:
 # quoted packet are the same.
 TARGETS +=	ping-mtu ping6-mtu
 
-run-regress-ping-mtu: addr.py
+run-regress-ping-mtu: addr.py stamp-pfctl
 	@echo '\n======== $@ ========'
-.for ip in DST_IN RDR_IN
+.for ip in ECO_IN RDR_IN
 	@echo Check path MTU to ${ip} is 1300
-	${SUDO} python2.7 ping_mtu.py ${${ip}} 1300
+	${SUDO} ${PYTHON}ping_mtu.py ${${ip}} 1300
 .endfor
 	@echo Check path MTU to AF_IN is 1280
-	${SUDO} python2.7 ping_mtu.py ${AF_IN} 1280
+	${SUDO} ${PYTHON}ping_mtu.py ${AF_IN} 1280
 
-run-regress-ping6-mtu: addr.py
+run-regress-ping6-mtu: addr.py stamp-pfctl
 	@echo '\n======== $@ ========'
-.for ip in DST_IN RDR_IN
+.for ip in ECO_IN RDR_IN
 	@echo Check path MTU to ${ip}6 is 1300
-	${SUDO} python2.7 ping6_mtu.py ${${ip}6} 1300
+	${SUDO} ${PYTHON}ping6_mtu.py ${${ip}6} 1300
 .endfor
 	@echo Check path MTU to AF_IN6 is 1320
-	${SUDO} python2.7 ping6_mtu.py ${AF_IN6} 1320
+	${SUDO} ${PYTHON}ping6_mtu.py ${AF_IN6} 1320
 
 # Send one udp echo port 7 packet to all destination addresses with netcat.
 # The response must arrive in 1 second.
 TARGETS +=	udp  udp6
 
-run-regress-udp:
+run-regress-udp: stamp-pfctl
 	@echo '\n======== $@ ========'
-.for ip in DST_IN RDR_IN AF_IN
+.for ip in ECO_IN RDR_IN AF_IN
 	@echo Check udp ${ip}:
 	( echo $$$$ | nc -u ${${ip}} 7 & sleep 1; kill $$! ) | grep $$$$
 .endfor
 
-run-regress-udp6:
+run-regress-udp6: stamp-pfctl
 	@echo '\n======== $@ ========'
-.for ip in DST_IN RDR_IN AF_IN
+.for ip in ECO_IN RDR_IN AF_IN
 	@echo Check udp ${ip}6:
 	( echo $$$$ | nc -u ${${ip}6} 7 & sleep 1; kill $$! ) | grep $$$$
 .endfor
@@ -174,22 +181,105 @@ run-regress-udp6:
 # Count the reflected bytes and compare with the transmitted ones.
 TARGETS +=	tcp  tcp6
 
-run-regress-tcp:
+run-regress-tcp: stamp-pfctl
 	@echo '\n======== $@ ========'
-.for ip in DST_IN RDR_IN AF_IN
+.for ip in ECO_IN RDR_IN AF_IN
 	@echo Check tcp ${ip}:
-	openssl rand 200000 | nc ${${ip}} 7 | wc -c | grep '200000$$'
+	openssl rand 200000 | nc -N ${${ip}} 7 | wc -c | grep '200000$$'
 .endfor
 
-run-regress-tcp6:
+run-regress-tcp6: stamp-pfctl
 	@echo '\n======== $@ ========'
-.for ip in DST_IN RDR_IN AF_IN
+.for ip in ECO_IN RDR_IN AF_IN
 	@echo Check tcp ${ip}6:
-	openssl rand 200000 | nc ${${ip}6} 7 | wc -c | grep '200000$$'
+	openssl rand 200000 | nc -N ${${ip}6} 7 | wc -c | grep '200000$$'
 .endfor
 
 REGRESS_TARGETS =	${TARGETS:S/^/run-regress-/}
 
-CLEANFILES +=		addr.py *.pyc *.log
+CLEANFILES +=		addr.py *.pyc *.log stamp-*
+
+.PHONY: check-setup
+
+# Check wether the address, route and remote setup is correct
+check-setup:
+	@echo '\n======== $@ SRC ========'
+	ping -n -c 1 ${SRC_OUT}  # SRC_OUT
+	route -n get -inet ${SRC_OUT} | fgrep -q 'interface: lo0'  # SRC_OUT
+	ping -n -c 1 ${PF_IN}  # PF_IN
+	route -n get -inet ${PF_IN} | fgrep -q 'interface: ${SRC_IF}'  # PF_IN SRC_IF
+.for ip in PF_OUT RT_IN RT_OUT ECO_IN RDR_IN AF_IN
+	route -n get -inet ${${ip}} | fgrep -q 'gateway: ${PF_IN}'  # ${ip} PF_IN
+.endfor
+	ping6 -n -c 1 ${SRC_OUT6}  # SRC_OUT6
+	route -n get -inet6 ${SRC_OUT6} | fgrep -q 'interface: lo0'  # SRC_OUT6
+	ping6 -n -c 1 ${PF_IN6}  # PF_IN6
+	route -n get -inet6 ${PF_IN6} | fgrep -q 'interface: ${SRC_IF}'  # PF_IN6 SRC_IF
+.for ip in PF_OUT RT_IN RT_OUT ECO_IN RDR_IN AF_IN
+	route -n get -inet6 ${${ip}6} | fgrep -q 'gateway: ${PF_IN6}'  # ${ip}6 PF_IN6
+.endfor
+	@echo '\n======== $@ PF ========'
+	ssh ${PF_SSH} ping -n -c 1 ${PF_IN}  # PF_IN
+	ssh ${PF_SSH} route -n get -inet ${PF_IN} | fgrep -q 'interface: lo0'  # PF_IN
+	ssh ${PF_SSH} ping -n -c 1 ${SRC_OUT}  # SRC_OUT
+	ssh ${PF_SSH} ping -n -c 1 ${PF_OUT}  # PF_OUT
+	ssh ${PF_SSH} route -n get -inet ${PF_OUT} | fgrep -q 'interface: lo0'  # PF_OUT
+	ssh ${PF_SSH} ping -n -c 1 ${RT_IN}  # RT_IN
+.for ip in RT_OUT ECO_IN
+	ssh ${PF_SSH} route -n get -inet ${${ip}} | fgrep -q 'gateway: ${RT_IN}'  # ${ip} RT_IN
+.endfor
+	ssh ${PF_SSH} ping6 -n -c 1 ${PF_IN6}  # PF_IN6
+	ssh ${PF_SSH} route -n get -inet6 ${PF_IN6} | fgrep -q 'interface: lo0'  # PF_IN6
+	ssh ${PF_SSH} ping6 -n -c 1 ${SRC_OUT6}  # SRC_OUT6
+	ssh ${PF_SSH} ping6 -n -c 1 ${PF_OUT6}  # PF_OUT6
+	ssh ${PF_SSH} route -n get -inet6 ${PF_OUT6} | fgrep -q 'interface: lo0'  # PF_OUT6
+	ssh ${PF_SSH} ping6 -n -c 1 ${RT_IN6}  # RT_IN6
+.for ip in RT_OUT ECO_IN
+	ssh ${PF_SSH} route -n get -inet6 ${${ip}6} | fgrep -q 'gateway: ${RT_IN6}'  # ${ip}6 RT_IN6
+.endfor
+	ssh ${PF_SSH} ${SUDO} pfctl -sr | grep '^anchor "regress" all$$'
+	ssh ${PF_SSH} ${SUDO} pfctl -si | grep '^Status: Enabled '
+	ssh ${PF_SSH} sysctl net.inet.ip.forwarding | fgrep =1
+	ssh ${PF_SSH} sysctl net.inet6.ip6.forwarding | fgrep =1
+	@echo '\n======== $@ RT ========'
+	ssh ${RT_SSH} ping -n -c 1 ${RT_IN}  # RT_IN
+	ssh ${RT_SSH} route -n get -inet ${RT_IN} | fgrep -q 'interface: lo0'  # RT_IN
+	ssh ${RT_SSH} ping -n -c 1 ${PF_OUT}  # PF_OUT
+.for ip in PF_IN SRC_OUT
+	ssh ${RT_SSH} route -n get -inet ${${ip}} | fgrep -q 'gateway: ${PF_OUT}'  # ${ip} PF_OUT
+.endfor
+	ssh ${RT_SSH} ping -n -c 1 ${RT_OUT}  # RT_OUT
+	ssh ${RT_SSH} route -n get -inet ${RT_OUT} | fgrep -q 'interface: lo0'  # RT_OUT
+	ssh ${RT_SSH} ping -n -c 1 ${ECO_IN}  # ECO_IN
+	ssh ${RT_SSH} ping6 -n -c 1 ${RT_IN6}  # RT_IN6
+	ssh ${RT_SSH} route -n get -inet6 ${RT_IN6} | fgrep -q 'interface: lo0'  # RT_IN6
+	ssh ${RT_SSH} ping6 -n -c 1 ${PF_OUT6}  # PF_OUT6
+.for ip in PF_IN SRC_OUT
+	ssh ${RT_SSH} route -n get -inet6 ${${ip}6} | fgrep -q 'gateway: ${PF_OUT6}'  # ${ip}6 PF_OUT6
+.endfor
+	ssh ${RT_SSH} ping6 -n -c 1 ${RT_OUT6}  # RT_OUT6
+	ssh ${RT_SSH} route -n get -inet6 ${RT_OUT6} | fgrep -q 'interface: lo0'  # RT_OUT6
+	ssh ${RT_SSH} ping6 -n -c 1 ${ECO_IN6}  # ECO_IN6
+	ssh ${RT_SSH} sysctl net.inet.ip.forwarding | fgrep =1
+	ssh ${RT_SSH} sysctl net.inet6.ip6.forwarding | fgrep =1
+	ssh ${RT_SSH} ifconfig | fgrep 'mtu 1300'
+	@echo '\n======== $@ ECO ========'
+	ssh ${ECO_SSH} ping -n -c 1 ${ECO_IN}  # ECO_IN
+	ssh ${ECO_SSH} route -n get -inet ${ECO_IN} | fgrep -q 'interface: lo0'  # ECO_IN
+	ssh ${ECO_SSH} ping -n -c 1 ${RT_OUT}  # RT_OUT
+.for ip in RT_IN PF_OUT PF_IN SRC_OUT
+	ssh ${ECO_SSH} route -n get -inet ${${ip}} | fgrep -q 'gateway: ${RT_OUT}'  # ${ip} RT_OUT
+.endfor
+	ssh ${ECO_SSH} ping6 -n -c 1 ${ECO_IN6}  # ECO_IN6
+	ssh ${ECO_SSH} route -n get -inet6 ${ECO_IN6} | fgrep -q 'interface: lo0'  # ECO_IN6
+	ssh ${ECO_SSH} ping6 -n -c 1 ${RT_OUT6}  # RT_OUT6
+.for ip in RT_IN PF_OUT PF_IN SRC_OUT
+	ssh ${ECO_SSH} route -n get -inet6 ${${ip}6} | fgrep -q 'gateway: ${RT_OUT6}'  # ${ip}6 RT_OUT6
+.endfor
+.for af in inet inet6
+.for proto in udp tcp
+	ssh ${ECO_SSH} netstat -a -f ${af} -p ${proto} | fgrep ' *.echo '
+.endfor
+.endfor
 
 .include <bsd.regress.mk>
